### ISSUE TITLE
How to compile JSX into UVDOM?

### ISSUE THREAD

**Issue by volkanunsal** [gcanti/uvdom#3]
I have an interesting use case where I need to turn a React class into a JSON string and save it in the server. I figured the best intermediate representation for this would be UVDOM, but I'm having trouble finding how to transform JSX into UVDOM. Is this a supported workflow?

**Comment by gcanti** [comment]
Take a look at this library I wrote:

https://github.com/gcanti/react-vdom

It's for testing purposes but maybe can be helpful.

I never tested the cycle:

```
react class -> uvdom (via react-vdom) -> react class (via uvdom)
```

but both libs should be compatible (except for the event handlers).

**Comment by volkanunsal** [comment]
That's exactly what I was looking for. Great job, as always. :+1:
